language: elixir
elixir:
- 1.6.6
otp_release:
- 21.0.1
services:
- postgresql
addons:
  postgresql: '9.5'
  chrome: stable
install:
- wget -N http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- sudo apt-get install -y postgresql-9.5-postgis-2.3
- sudo service postgresql restart
- mix local.rebar --force
- mix local.hex --force
- mix deps.get
script:
- mix format --check-formatted && mix credo --strict
- MIX_ENV=test mix do ecto.create, ecto.migrate && mix coveralls.travis --umbrella
- cd $TRAVIS_BUILD_DIR/apps/bus_detective_web/assets && npm install
- cd $TRAVIS_BUILD_DIR/apps/bus_detective_web/assets && ./node_modules/.bin/eslint js/**/*.js
- cd $TRAVIS_BUILD_DIR/apps/bus_detective_web/assets && node node_modules/webpack/bin/webpack.js --mode development
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: heroku
  api_key:
    secure: mCaAH41QErmYnfJAxjPxrIbs2oob3FMSrjh/XzU5zJekkrNXi6C2ztWrygjfnxkULDl03Sdcth+uOYeoIMn1+GhyFhWk5lBz+3noPW/qjsM4+nsIDqmufq6rE6sz/jYV67y5541BVtmPWG/zBRFkBErmg0ezTV4d5+zf+K3QsnkY3285GrXK1C30YhVbQpNKuqoj+ZAy433EcTWULpwTHbrcfwYZWr8V5s4UEker9EMZ3fedk/hiE51wwZwDt+JRWalcfs/ZbUeQzUqxKiL30Xa6dLmBtal5Iad0sYg15Lw7HJ7cDm99z9iO4raFo90ir6QFJES9sZMy3EzrI0o+jsnXImKkk666ckwFBH4jK6hl1/jNnQJ+tESrIE4moN+M18qe5Oe9rL3c57EauFHu+jHKU8BpfKt29p2uu66G/dgeP7u2WHj/9dzixd+0BzbP0f1Kut+YzVnFgbnHxSqnoL/CTsPhabqleVgxvht91UrRR9LcsJH+LGTGxJKju2fQcOYXOeJPSdAg0ZFN2OveGdOxhKnnlaxk6ZRtXT/lVEZmXXnz2cSOJkA015Vvv8tePNMyfLGmr4+Q9SwT3PrwCtE38z8eKlNFydsOwlU12uF3sGSmkRHkBYezf6NUwPna21Tv8EB6pXZOBoZTvmt5r1B9u+vN1vYfyG7v1ZdIouc=
  app:
    master: busdetective-ng-staging
  on:
    repo: bus-detective/bus_detective_ng
  run: mix ecto.migrate
