language: elixir

elixir:
  - 1.6.6

otp_release:
  - 21.0.1

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

script:
  - MIX_ENV=test mix do ecto.create, ecto.migrate
  - mix test
